// src/viz/index.js — viz registry barrel.
//
// To add a new interactive visualisation:
//   1. Create a JSX file in this directory that default-exports a React component.
//   2. Import it here and call `register("<id>", Component)`.
//   3. Reference it from any markdown file with:  ::: viz <id> "optional caption"
//
// The string id is what authors type in markdown. Keep it short, lowercase, stable.

import { register } from "../framework/viz-registry.js";

import Rasterize from "./rasterize.jsx";
import Ray from "./ray.jsx";
import BFS from "./bfs.jsx";
import BTree from "./btree.jsx";
import Handshake from "./handshake.jsx";
import BiasVar from "./biasvar.jsx";
import PisMonoVsMicro from "./pis-mono-vs-micro.jsx";
import CdiScopes from "./cdi-scopes.jsx";
import JpaInheritance from "./jpa-inheritance.jsx";
import OAuth2Flow from "./oauth2-flow.jsx";
import Benes from "./benes.jsx";
import Clos from "./clos.jsx";
import HolVoq from "./holvoq.jsx";
import Dijkstra from "./dijkstra.jsx";
import Kademlia from "./kademlia.jsx";
import HiCuts from "./hicuts.jsx";
import CountToInf from "./count-to-inf.jsx";
import ISlip from "./islip.jsx";
import AIMD from "./aimd.jsx";
import P2POverlay from "./p2p-overlay.jsx";
import OlapCube from "./olap-cube.jsx";
import JpaLifecycle from "./jpa-lifecycle.jsx";
import JpaNplus1 from "./jpa-nplus1.jsx";
import TwoPhaseCommit from "./two-phase-commit.jsx";
import Saga from "./saga.jsx";
import WorkflowPatterns from "./workflow-patterns.jsx";
import RecoverableQueue from "./recoverable-queue.jsx";
import NfaToDfa from "./nfa-to-dfa.jsx";
import AmdahlGustafson from "./amdahl-gustafson.jsx";
import BroadcastRedukce from "./broadcast-redukce.jsx";
import PrefixSumUvod from "./prefix-sum-uvod.jsx";
import PrefixSumAlgoritmus from "./prefix-sum-algoritmus.jsx";
import EulerTour from "./euler-tour.jsx";
import KontrakceUvod from "./kontrakce-uvod.jsx";
import TranspositionEnumeration from "./transposition-enumeration.jsx";
import MergeRadici from "./merge-radici.jsx";
import NasobeniMaticMesh from "./nasobeni-matic-mesh.jsx";
import VolbaMaster from "./volba-master.jsx";
import RaftPraxe from "./raft-praxe.jsx";
import EnumerationSort from "./enumeration-sort.jsx";
import MinExtractionSort from "./min-extraction-sort.jsx";
import MedianSplitting from "./median-splitting.jsx";
import ListRanking from "./list-ranking.jsx";
import OmegaNetwork from "./omega-network.jsx";
import CaesarShift from "./caesar-shift.jsx";
import TmSimulator from "./tm-simulator.jsx";
import PdaStack from "./pda-stack.jsx";
import CfgDerivation from "./cfg-derivation.jsx";
import CykParsing from "./cyk-parsing.jsx";
import DfaMinimization from "./dfa-minimization.jsx";
import PumpingLemma from "./pumping-lemma.jsx";
import MasterTheorem from "./master-theorem.jsx";
import ReductionWiring from "./reduction-wiring.jsx";
import SatClique from "./sat-clique.jsx";
import ChomskyHierarchy from "./chomsky-hierarchy.jsx";
import VigenereAttack from "./vigenere-attack.jsx";
import FreqAnalysis from "./freq-analysis.jsx";
import Enigma from "./enigma.jsx";
import EcbTux from "./ecb-tux.jsx";
import Feistel from "./feistel.jsx";
import AesRound from "./aes-round.jsx";
import DhMitm from "./dh-mitm.jsx";
import EcPointAdd from "./ec-point-add.jsx";
import RsaToy from "./rsa-toy.jsx";
import PaddingOracle from "./padding-oracle.jsx";
import BirthdayParadox from "./birthday-paradox.jsx";
import MerkleDamgard from "./merkle-damgard.jsx";
import Sponge from "./sponge.jsx";
import KerberosViz from "./kerberos.jsx";
import NeedhamSchroeder from "./needham-schroeder.jsx";
import EcdsaNonceReuse from "./ecdsa-nonce-reuse.jsx";
import HillCipher from "./hill-cipher.jsx";
import Playfair from "./playfair.jsx";
import RotorPeriod from "./rotor-period.jsx";
import ColumnarTransposition from "./columnar-transposition.jsx";
import OtpCribDrag from "./otp-crib-drag.jsx";
import Tls13Handshake from "./tls13-handshake.jsx";
import PollardRho from "./pollard-rho.jsx";
import SquareAndMultiply from "./square-and-multiply.jsx";
import HmacStructure from "./hmac-structure.jsx";
import LsbSteganografie from "./lsb-steganografie.jsx";

register("rasterize",         Rasterize);
register("ray",               Ray);
register("bfs",               BFS);
register("btree",             BTree);
register("handshake",         Handshake);
register("biasvar",           BiasVar);
register("pis-mono-vs-micro", PisMonoVsMicro);
register("cdi-scopes",        CdiScopes);
register("jpa-inheritance",   JpaInheritance);
register("oauth2-flow",       OAuth2Flow);
register("benes",             Benes);
register("clos",              Clos);
register("hol-voq",           HolVoq);
register("dijkstra",          Dijkstra);
register("kademlia",          Kademlia);
register("hicuts",            HiCuts);
register("count-to-inf",      CountToInf);
register("islip",             ISlip);
register("aimd",              AIMD);
register("p2p-overlay",       P2POverlay);
register("olap-cube",         OlapCube);
register("jpa-lifecycle",     JpaLifecycle);
register("jpa-nplus1",        JpaNplus1);
register("two-phase-commit",  TwoPhaseCommit);
register("saga",              Saga);
register("workflow-patterns", WorkflowPatterns);
register("recoverable-queue", RecoverableQueue);
register("nfa-to-dfa",        NfaToDfa);
register("amdahl-gustafson",  AmdahlGustafson);
register("broadcast-redukce", BroadcastRedukce);
register("prefix-sum-uvod",   PrefixSumUvod);
register("prefix-sum-algoritmus", PrefixSumAlgoritmus);
register("euler-tour",        EulerTour);
register("kontrakce-uvod",    KontrakceUvod);
register("transposition-enumeration", TranspositionEnumeration);
register("merge-radici",      MergeRadici);
register("nasobeni-matic-mesh", NasobeniMaticMesh);
register("volba-master",      VolbaMaster);
register("raft-praxe",        RaftPraxe);
register("enumeration-sort", EnumerationSort);
register("min-extraction-sort", MinExtractionSort);
register("median-splitting", MedianSplitting);
register("list-ranking", ListRanking);
register("omega-network", OmegaNetwork);
register("caesar-shift", CaesarShift);
register("tm-simulator", TmSimulator);
register("pda-stack", PdaStack);
register("cfg-derivation", CfgDerivation);
register("cyk-parsing", CykParsing);
register("dfa-minimization", DfaMinimization);
register("pumping-lemma", PumpingLemma);
register("master-theorem", MasterTheorem);
register("reduction-wiring", ReductionWiring);
register("sat-clique", SatClique);
register("chomsky-hierarchy", ChomskyHierarchy);
register("vigenere-attack", VigenereAttack);
register("freq-analysis", FreqAnalysis);
register("enigma", Enigma);
register("ecb-tux", EcbTux);
register("feistel", Feistel);
register("aes-round", AesRound);
register("dh-mitm", DhMitm);
register("ec-point-add", EcPointAdd);
register("rsa-toy", RsaToy);
register("padding-oracle", PaddingOracle);
register("birthday-paradox", BirthdayParadox);
register("merkle-damgard", MerkleDamgard);
register("sponge", Sponge);
register("kerberos", KerberosViz);
register("needham-schroeder", NeedhamSchroeder);
register("ecdsa-nonce-reuse", EcdsaNonceReuse);
register("hill-cipher", HillCipher);
register("playfair", Playfair);
register("rotor-period", RotorPeriod);
register("columnar-transposition", ColumnarTransposition);
register("otp-crib-drag", OtpCribDrag);
register("tls13-handshake", Tls13Handshake);
register("pollard-rho", PollardRho);
register("square-and-multiply", SquareAndMultiply);
register("hmac-structure", HmacStructure);
register("lsb-steganografie", LsbSteganografie);
